import { sections } from './app/catalog.js'

const root = document.querySelector('#root')
const labels = { name: 'Nome', description: 'Descrição', locale: 'Localidade', currency: 'Moeda', markets: 'Mercados', languages: 'Idiomas', status: 'Estado', platform: 'Plataforma', category: 'Categoria', product: 'Produto', market: 'Mercado', offer: 'Oferta', destination: 'Destino', capability: 'Capacidade' }
let page = 'dashboard'
const value = (item) => Array.isArray(item) ? item.join(' · ') : item
const editable = (entry, field) => Array.isArray(entry[field]) ? entry[field].join(', ') : (entry[field] ?? '')

function navigation() { return `<aside><button class="brand" data-page="dashboard" aria-label="Ir ao dashboard"><span>M</span><b>Mavuri</b><em>Affiliate Engine</em></button><nav aria-label="Navegação principal"><button class="${page === 'dashboard' ? 'active' : ''}" data-page="dashboard">Visão geral</button><p>Administração</p>${sections.map((s) => `<button class="${page === s.id ? 'active' : ''}" data-page="${s.id}">${s.label}</button>`).join('')}</nav><footer>Fundação MVP<br>Dados locais em memória</footer></aside>` }
function dashboard() { return `<header class="page-heading"><p class="eyebrow">MVP · ambiente local</p><h1>Fundação do Affiliate Engine</h1><p>Uma visão navegável do domínio para validar a organização inicial, sem publicar, importar ou integrar dados externos.</p></header><section class="status-card"><div><p class="eyebrow">Estado atual</p><h2>Interface administrativa em modo demonstrativo</h2><p>Agora os catálogos também permitem cadastro, edição e exclusão durante a sessão.</p></div><span class="status-dot">Sem integrações externas</span></section><section><div class="section-title"><h2>Áreas disponíveis</h2><p>Escolha uma área para consultar e administrar os dados locais.</p></div><div class="area-grid">${sections.map((s) => `<button class="area-card" data-page="${s.id}"><span>${s.eyebrow}</span><strong>${s.label}</strong><small>${s.repository.list().length} registro(s) local(is)</small></button>`).join('')}</div></section><section class="next-steps"><h2>Limites desta etapa</h2><ul><li>As alterações existem apenas enquanto a página permanece aberta.</li><li>Nenhuma autenticação, automação, scraping ou publicação real foi implementada.</li><li>Telegram continua apenas como canal conceitual, sem credenciais ou chamadas de API.</li></ul></section>` }
function fieldInput(entry, field) { return `<label><span>${labels[field]}</span><input name="${field}" value="${String(editable(entry, field)).replaceAll('&', '&amp;').replaceAll('"', '&quot;')}" /></label>` }
function sectionPage(s) { const entries = s.repository.list(); return `<header class="page-heading"><p class="eyebrow">${s.eyebrow}</p><div class="heading-row"><div><h1>${s.title}</h1><p>${s.intro}</p></div><button class="primary" data-add="${s.id}">+ Novo cadastro</button></div></header><section class="catalog" aria-label="${s.title}">${entries.length ? entries.map((entry) => `<article class="entry"><div><h2>${entry.name}</h2><p>${entry.description}</p></div><dl>${s.fields.map((field) => `<div><dt>${labels[field]}</dt><dd>${value(entry[field])}</dd></div>`).join('')}</dl><div class="entry-actions"><button data-edit="${entry.id}">Editar</button><button class="danger" data-remove="${entry.id}">Excluir</button></div></article>`).join('') : `<div class="empty">Nenhum cadastro nesta área.</div>`}</section><p class="notice">Os dados desta etapa são mantidos somente em memória. Ao recarregar a página, o catálogo volta ao estado inicial.</p>` }
function formPage(s, entry = null) { const isEdit = Boolean(entry); const blank = Object.fromEntries(['name', 'description', ...s.fields].map((field) => [field, ''])); const record = entry || blank; return `<header class="page-heading"><p class="eyebrow">${s.eyebrow}</p><h1>${isEdit ? 'Editar cadastro' : 'Novo cadastro'}</h1><p>${s.label}</p></header><form class="editor" data-section="${s.id}" data-id="${entry?.id || ''}">${fieldInput(record, 'name')}${fieldInput(record, 'description')}${s.fields.map((field) => fieldInput(record, field)).join('')}<div class="form-actions"><button type="button" data-page="${s.id}">Cancelar</button><button class="primary" type="submit">${isEdit ? 'Salvar alterações' : 'Adicionar cadastro'}</button></div></form>` }
function render() { const section = sections.find((s) => s.id === page); const edit = page.startsWith('edit:') ? sections.find((s) => s.id === page.split(':')[1]) : null; const add = page.startsWith('add:') ? sections.find((s) => s.id === page.split(':')[1]) : null; const entry = edit ? edit.repository.list().find((item) => item.id === page.split(':')[2]) : null; root.innerHTML = `<div class="shell">${navigation()}<main>${edit ? formPage(edit, entry) : add ? formPage(add) : section ? sectionPage(section) : dashboard()}</main></div>`; bind() }
function bind() { root.querySelectorAll('[data-page]').forEach((button) => button.addEventListener('click', () => { page = button.dataset.page; render() })); root.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', () => { page = `add:${button.dataset.add}`; render() })); root.querySelectorAll('[data-edit]').forEach((button) => button.addEventListener('click', () => { const s = sections.find((item) => page === item.id); page = `edit:${s.id}:${button.dataset.edit}`; render() })); root.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => { const s = sections.find((item) => page === item.id); if (confirm('Excluir este cadastro local?')) { s.repository.remove(button.dataset.remove); render() } })); const form = root.querySelector('.editor'); if (form) form.addEventListener('submit', (event) => { event.preventDefault(); const s = sections.find((item) => item.id === form.dataset.section); const data = Object.fromEntries(new FormData(form)); s.fields.forEach((field) => { if (data[field]?.includes(',')) data[field] = data[field].split(',').map((item) => item.trim()).filter(Boolean) }); if (form.dataset.id) s.repository.update(form.dataset.id, data); else s.repository.create(data); page = s.id; render() }) }
render()
