import { sections } from './app/catalog.js'
import './styles.css'

const root = document.querySelector('#root')
const labels = { locale: 'Localidade', currency: 'Moeda', markets: 'Mercados', languages: 'Idiomas', status: 'Estado', platform: 'Plataforma', category: 'Categoria', product: 'Produto', market: 'Mercado', offer: 'Oferta', destination: 'Destino', capability: 'Capacidade' }
let page = 'dashboard'
const value = (item) => Array.isArray(item) ? item.join(' · ') : item

function navigation() { return `<aside><button class="brand" data-page="dashboard" aria-label="Ir ao dashboard"><span>M</span><b>Mavuri</b><em>Affiliate Engine</em></button><nav aria-label="Navegação principal"><button class="${page === 'dashboard' ? 'active' : ''}" data-page="dashboard">Visão geral</button><p>Administração</p>${sections.map((s) => `<button class="${page === s.id ? 'active' : ''}" data-page="${s.id}">${s.label}</button>`).join('')}</nav><footer>Fundação MVP<br>Dados de desenvolvimento</footer></aside>` }
function dashboard() { return `<header class="page-heading"><p class="eyebrow">MVP · ambiente local</p><h1>Fundação do Affiliate Engine</h1><p>Uma visão navegável do domínio para validar a organização inicial, sem publicar, importar ou integrar dados externos.</p></header><section class="status-card"><div><p class="eyebrow">Estado atual</p><h2>Interface administrativa em modo demonstrativo</h2><p>Os registros abaixo são dados locais. Eles existem para tornar os vínculos do domínio visíveis durante o desenvolvimento.</p></div><span class="status-dot">Sem integrações externas</span></section><section><div class="section-title"><h2>Áreas disponíveis</h2><p>Escolha uma área para consultar os dados de desenvolvimento.</p></div><div class="area-grid">${sections.map((s) => `<button class="area-card" data-page="${s.id}"><span>${s.eyebrow}</span><strong>${s.label}</strong><small>${s.repository.list().length} registro(s) local(is)</small></button>`).join('')}</div></section><section class="next-steps"><h2>Limites desta etapa</h2><ul><li>Nenhuma autenticação, automação, scraping ou publicação real foi implementada.</li><li>Telegram aparece como canal conceitual; não há credenciais, chamadas de API ou destinos configurados.</li><li>A troca dos catálogos locais por repositórios de API ou banco está isolada na infraestrutura.</li></ul></section>` }
function sectionPage(s) { const entries = s.repository.list(); return `<header class="page-heading"><p class="eyebrow">${s.eyebrow}</p><div class="heading-row"><div><h1>${s.title}</h1><p>${s.intro}</p></div><span class="local-badge">Dados locais</span></div></header><section class="catalog" aria-label="${s.title}">${entries.map((entry) => `<article class="entry"><div><h2>${entry.name}</h2><p>${entry.description}</p></div><dl>${s.fields.map((field) => `<div><dt>${labels[field]}</dt><dd>${value(entry[field])}</dd></div>`).join('')}</dl></article>`).join('')}</section><p class="notice">Cadastro, edição e persistência serão adicionados após a definição do modelo físico, regras de validação e acesso.</p>` }
function render() { const section = sections.find((s) => s.id === page); root.innerHTML = `<div class="shell">${navigation()}<main>${section ? sectionPage(section) : dashboard()}</main></div>`; root.querySelectorAll('[data-page]').forEach((button) => button.addEventListener('click', () => { page = button.dataset.page; render() })) }
render()

